# Generated by Django 4.0.5 on 2022-06-05 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс'),
        ),
        migrations.CreateModel(
            name='RequestCreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a', 'Депозитный'), ('b', 'Кредитный')], max_length=1, verbose_name='Вид счёта')),
                ('currency', models.CharField(choices=[('r', 'Рубли'), ('d', 'Доллары'), ('e', 'Евро')], max_length=1, verbose_name='Валюта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'request_create_account',
            },
        ),
    ]
